source 'https://rubygems.org'

ruby '2.2.0'

gem 'compass'
gem 'dotenv'
gem 'haml'
gem 'newrelic_rpm'
gem 'pg'
gem 'rake'
gem 'sidekiq'
gem 'sinatra',                require: 'sinatra/base'
gem 'sinatra-activerecord',   require: 'sinatra/activerecord'
gem 'sinatra-asset-pipeline', require: 'sinatra/asset_pipeline'
gem 'sinatra-contrib',        require: 'sinatra/contrib'
gem 'sinatra-partial',        require: 'sinatra/partial'
gem 'tilt', '1.4.1'
gem 'uglifier'
gem 'unicorn'

group :test, :development do
  gem 'better_errors'
  gem 'pry'
  gem 'rack-test'
  gem 'rspec'
  gem 'shotgun'
end
